#!/usr/bin/env python3
import sys
import os
import struct
from instruction_set import decode, format_operand, OPCODES

ROM_FILE = "VS. Battle City (1985)(Namco).nes"
LABELS_FILE = "labels.csv"
COMMENTS_FILE = "comments.csv"

class NESRom:
    def __init__(self, path):
        with open(path, 'rb') as f:
            self.raw = f.read()
        if self.raw[:4] != b'NES\x1a':
            raise ValueError("Not a valid iNES ROM")
        self.prg_banks = self.raw[4]
        self.chr_banks = self.raw[5]
        self.has_trainer = bool(self.raw[6] & 0x04)
        self.prg_start = 16 + (512 if self.has_trainer else 0)
        self.prg_size = self.prg_banks * 16384
        self.prg = self.raw[self.prg_start : self.prg_start + self.prg_size]
        self.chr_start = self.prg_start + self.prg_size
        self.chr_size = self.chr_banks * 8192
        self.chr = self.raw[self.chr_start : self.chr_start + self.chr_size]

    def cpu_to_prg_offset(self, cpu_addr):
        return cpu_addr - 0x8000

def load_knowledge(path):
    data = {}
    if not os.path.exists(path):
        return data
    import csv
    with open(path, newline='') as f:
        for row in csv.reader(f):
            if not row or row[0].startswith('#'): continue
            if len(row) < 3: continue
            bank_s, addr_s, val = row[0].strip(), row[1].strip(), row[2].strip()
            try:
                bank = int(bank_s, 16) if bank_s not in ('', '*') else None
                addr = int(addr_s, 16)
                data[(bank, addr)] = val
            except ValueError: pass
    return data

def get_kv(data, bank, addr):
    return data.get((bank, addr)) or data.get((None, addr))

# Formatting helpers
def fmt_hex8(data, addr, labels, bank):
    return f"  ${addr:04X}  {data[0]:02X}        .byte ${data[0]:02X}"

def fmt_u8(data, addr, labels, bank):
    return f"  ${addr:04X}  {data[0]:02X}        .byte ${data[0]:02X}  ; {data[0]:d}"

def fmt_s8(data, addr, labels, bank):
    v = data[0]
    sv = v if v < 128 else v - 256
    return f"  ${addr:04X}  {v:02X}        .byte ${v:02X}  ; {sv:+d}"

def fmt_ptr16(data, addr, labels, bank):
    ptr = data[0] | (data[1] << 8)
    lbl = get_kv(labels, bank, ptr)
    note = f" -> {lbl}" if lbl else ""
    return f"  ${addr:04X}  {data[0]:02X} {data[1]:02X}     .word ${ptr:04X}{note}"

def fmt_u16(data, addr, labels, bank):
    v = data[0] | (data[1] << 8)
    return f"  ${addr:04X}  {data[0]:02X} {data[1]:02X}     .word ${v:04X}  ; {v:d}"

# Range definitions
# (bank, start, end, type, metadata)
RANGES = [
    # BANK 0
    (0, 0x8000, 0x801A, 'ptr16', 'LevelCodePtrs'),
    (0, 0x801A, 0x8034, 'ptr16', 'LevelFormationPtrs'),
    (0, 0x8034, 0x80A4, 'ptr16', 'InnerFormationTables'),
    (0, 0x80A4, 0x80B6, 'u8', 'InnerTablesData'),
    (0, 0x80B6, 0x80C3, 'u8', 'StageFlagsTable'),
    (0, 0x80C3, 0x82F4, 'hex8', None),
    (0, 0x82F4, 0x8312, 'u8', 'SpriteTables'),
    (0, 0x8312, 0x8316, 'u8', 'WaveControlInit'),
    (0, 0x8316, 0x8348, 'hex8', None),
    (0, 0x8348, 0x8360, 'u8', 'PtrTablesAB'),
    (0, 0x8360, 0x83A2, 'u8', 'EntitySlotData'),
    (0, 0x83A2, 0x83AD, 'hex8', None),
    (0, 0x83AD, 0x83B3, 'u8', 'StageNumLUT'),
    (0, 0x83B3, 0x86E0, 'code', None),
    (0, 0x86E0, 0x874D, 'code', 'StageLoader'),
    (0, 0x874D, 0xF239, 'code', None),
    (0, 0xF239, 0xF27D, 'code', 'LevelTileLoader'),
    (0, 0xF27D, 0xFFF0, 'hex8', 'LevelMapData'),
    (0, 0xFFF0, 0xC000, 'hex8', 'Padding'), # Transition to Bank 1

    # BANK 1
    (1, 0xC000, 0xC070, 'hex8', 'Padding'),
    (1, 0xC070, 0xD1A7, 'code', None),
    (1, 0xD1A7, 0xD212, 'hex8', 'TitleStrings'),
    (1, 0xD212, 0xD44A, 'code', None),
    (1, 0xD44A, 0xD46A, 'u8', 'PaletteData'),
    (1, 0xD46A, 0xD475, 'code', 'PaletteApplyDIP'),
    (1, 0xD475, 0xD575, 'u8', 'PaletteColorTable'),
    (1, 0xD575, 0xE529, 'code', None),
    (1, 0xE529, 0xE531, 's8', 'DirDeltaTable'),
    (1, 0xE531, 0xE537, 'u8', 'EnemySpawnX'),
    (1, 0xE537, 0xE539, 'u8', 'PlayerSpawnX'),
    (1, 0xE539, 0xE53B, 'u8', 'PlayerSpawnY'),
    (1, 0xE53B, 0xE543, 'u8', 'InitState'),
    (1, 0xE543, 0xE555, 'u8', 'DirToStateTable'),
    (1, 0xE555, 0xE575, 'ptr16', 'MovementDispatch'),
    (1, 0xE575, 0xE595, 'ptr16', 'MoveUpdateDispatch'),
    (1, 0xE595, 0xE5A9, 'ptr16', 'BulletDispatch'),
    (1, 0xE5A9, 0xE5D1, 'u8', 'EnemyTypeTable'),
    (1, 0xE5D1, 0xE6A9, 'hex8', None),
    (1, 0xE6A9, 0xE739, 'u8', 'SpeedTable'),
    (1, 0xE739, 0xEE8B, 'code', None),
    (1, 0xEE8B, 0xEEA3, 'u16', 'NotePitchTable'),
    (1, 0xEEA3, 0xEEDC, 'ptr16', 'SoundSeqPtrTable'),
    (1, 0xEEDC, 0xFFFA, 'code', None),
    (1, 0xFFFA, 0x10000, 'ptr16', 'Vectors'),
]

def main():
    rom = NESRom(ROM_FILE)
    labels = load_knowledge(LABELS_FILE)
    comments = load_knowledge(COMMENTS_FILE)

    print(f"; VS. Battle City — Full ROM Listing")
    print(f"; Generated by gen_full_listing.py")
    print()

    for bank, start, end, rtype, metadata in RANGES:
        print(f"; ---------------------------------------------------------------------------")
        header = f"; Range ${start:04X}–${end:04X} ({rtype})"
        if metadata: header += f" {metadata}"
        print(header)
        print(f"; ---------------------------------------------------------------------------")

        addr = start
        while addr < end:
            # Labels and comments
            lbl = get_kv(labels, bank, addr)
            if lbl: print(f"\n{lbl}:")
            cmt = get_kv(comments, bank, addr)
            cmt_s = f" ; {cmt}" if cmt else ""

            if rtype == 'code':
                off = rom.cpu_to_prg_offset(addr)
                if off >= len(rom.prg): break
                mnemonic, mode, length, cycles, operand = decode(rom.prg, off)
                byte_str = ' '.join(f'{b:02X}' for b in rom.prg[off:off+length])
                
                # Resolving labels for operands
                bank_labels = {a: n for (b, a), n in labels.items() if b is None or b == bank}
                op_str = format_operand(mode, operand, addr + length, bank_labels)
                
                print(f"  ${addr:04X}  {byte_str:<8}  {mnemonic} {op_str}{cmt_s}")
                addr += length
            elif rtype == 'ptr16' or rtype == 'u16':
                off = rom.cpu_to_prg_offset(addr)
                if off + 1 >= len(rom.prg): break
                if rtype == 'ptr16': line = fmt_ptr16(rom.prg[off:off+2], addr, labels, bank)
                else: line = fmt_u16(rom.prg[off:off+2], addr, labels, bank)
                print(f"{line}{cmt_s}")
                addr += 2
            elif rtype in ('u8', 's8', 'hex8'):
                off = rom.cpu_to_prg_offset(addr)
                if off >= len(rom.prg): break
                if rtype == 'u8': line = fmt_u8(rom.prg[off:off+1], addr, labels, bank)
                elif rtype == 's8': line = fmt_s8(rom.prg[off:off+1], addr, labels, bank)
                else: line = fmt_hex8(rom.prg[off:off+1], addr, labels, bank)
                print(f"{line}{cmt_s}")
                addr += 1
            else:
                addr += 1

    # CHR-ROM dump
    print()
    print(f"; ---------------------------------------------------------------------------")
    print(f"; CHR-ROM ({len(rom.chr)} bytes)")
    print(f"; ---------------------------------------------------------------------------")
    for bidx in range(rom.chr_banks * 2): # 4KB banks
        start = bidx * 4096
        end = start + 4096
        print(f"\n; CHR Bank {bidx} ($0000-$0FFF in PPU space if selected)")
        for i in range(start, end, 16):
            chunk = rom.chr[i:i+16]
            hex_s = ' '.join(f'{b:02X}' for b in chunk)
            print(f"  {i:04X}  {hex_s}")

if __name__ == "__main__":
    main()
